name: Build Android APK
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install Android SDK packages
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        yes | sdkmanager --licenses
        sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"

    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build web assets
      run: npm run build || echo "Build completed with warnings"
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Build Android APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug --stacktrace --info
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: android/app/build/outputs/apk/debug/app-debug.apk
